(()=>{
const KEY='heroXPv11Extras';let extra;try{extra=JSON.parse(localStorage.getItem(KEY)||'null')}catch{};extra=extra||{missions:[],done:{},trophies:{},history:[]};
const el=id=>document.getElementById(id),escape=window.safe;
let cloud=null,cloudTimer=null;const config=window.HERO_CLOUD_CONFIG||{};
function persist(){localStorage.setItem(KEY,JSON.stringify(extra));queueSync()}
window.v11bridge={get:()=>extra,persist};
function record(type,ids,xp,hd,note){extra.history.unshift({date:new Date().toISOString(),type,students:ids.map(i=>students[i]?.name).filter(Boolean),xp,hd,note});extra.history=extra.history.slice(0,1000);persist()}
function show(title,body){el('v11Title').textContent=title;el('v11Body').innerHTML=body;el('v11Panel').classList.add('open')}
const period=m=>m.cadence==='daily'?new Date().toLocaleDateString('en-CA'):(()=>{let d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);return d.toLocaleDateString('en-CA')})();
window.openV11=k=>{if(k==='missions'){show('📜 Daily & Weekly Missions',`<p>Select students first. Each mission can be completed once per student per period.</p>${extra.missions.map(m=>`<div class="mission"><b>${escape(m.title)}</b> — ${m.cadence}<p>+${m.xp} XP, +$${m.hd}</p><button onclick="completeMission('${m.id}')">Complete for selected</button><button onclick="deleteMission('${m.id}')">Delete</button></div>`).join('')}<h3>New mission</h3><input id="mTitle" placeholder="Mission title"><select id="mCadence"><option value="daily">Daily</option><option value="weekly">Weekly</option></select><input id="mXP" type="number" value="5" min="0" max="1000" placeholder="XP"><input id="mHD" type="number" value="0" min="0" max="1000" placeholder="Hero Dollars"><button onclick="addMission()">Add Mission</button>`)}
if(k==='trophies'){let i=selected.size===1?[...selected][0]:-1,s=students[i];show('🏆 Trophy Room',s?`<h3>${escape(s.name)} — Level ${L(s.xp).l}</h3><p>${[10,25,50,75,100].filter(n=>L(s.xp).l>=n).map(n=>'🏅 Level '+n).concat(extra.trophies[s.name]||[]).map(escape).join(' • ')||'No trophies yet'}</p><input id="trophyTitle" placeholder="New trophy"><button onclick="awardTrophy()">Award Trophy</button>`:'Select exactly one student first.')}
if(k==='history'){show('📖 Reward History',`<button onclick="exportHistory()">Export CSV</button><p>Tracks new V11 actions; past V10 actions cannot be reconstructed.</p>${extra.history.slice(0,100).map(h=>`<div class="historyline">${escape(new Date(h.date).toLocaleString())} — ${escape(h.type)} — ${escape(h.students.join(', '))} — ${h.xp} XP / $${h.hd}<br>${escape(h.note||'')}</div>`).join('')||'No new events yet.'}`)}
if(k==='cloud'){show('☁️ Cloud Saving',`<p>${cloud?'Signed in':'Not signed in'} • Requires configured Supabase project and teacher account.</p><input id="cloudEmail" type="email" placeholder="Teacher email"><input id="cloudPassword" type="password" placeholder="Password"><button onclick="cloudLogin()">Sign in</button><button onclick="cloudPush()">Upload local snapshot</button><button onclick="cloudPull()">Download cloud snapshot</button><button onclick="cloudLogout()">Sign out</button><p>Always back up before downloading. Download replaces local balances and progress.</p>`)}}
window.addMission=()=>{let title=el('mTitle').value.trim(),xp=Number(el('mXP').value),hd=Number(el('mHD').value);if(!title||![xp,hd].every(n=>Number.isInteger(n)&&n>=0&&n<=1000))return toast('Enter a valid mission and rewards.');extra.missions.push({id:'m'+Date.now(),title:title.slice(0,100),cadence:el('mCadence').value,xp,hd});persist();openV11('missions')};
window.deleteMission=id=>{if(!confirm('Delete mission?'))return;extra.missions=extra.missions.filter(m=>m.id!==id);persist();openV11('missions')};
window.completeMission=id=>{let m=extra.missions.find(m=>m.id===id);if(!m||!selected.size)return toast('Select students first.');let ids=[...selected].filter(i=>!extra.done[id+'|'+students[i].name+'|'+period(m)]);if(!ids.length)return toast('Already completed this period.');if(ids.length>1&&!confirm('Award mission to '+ids.length+' students?'))return;let old=[...selected];selected=new Set(ids);if(m.xp)baseAward(m.xp,'Mission '+m.title);if(m.hd)baseDollars(m.hd);selected=new Set(old);ids.forEach(i=>extra.done[id+'|'+students[i].name+'|'+period(m)]=true);record('Mission',ids,m.xp,m.hd,m.title);render();openV11('missions')};
window.awardTrophy=()=>{if(selected.size!==1)return toast('Select one student.');let i=[...selected][0],name=el('trophyTitle').value.trim();if(!name)return;extra.trophies[students[i].name]??=[];if(!extra.trophies[students[i].name].includes(name))extra.trophies[students[i].name].push(name.slice(0,80));record('Trophy',[i],0,0,name);openV11('trophies')};
window.exportHistory=()=>{let lines=['Date,Type,Students,XP,Hero Dollars,Note'];for(let h of extra.history)lines.push([h.date,h.type,h.students.join('; '),h.xp,h.hd,h.note].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','));let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='hero-xp-history.csv';a.click()};
window.togglePresentation=()=>{document.body.classList.toggle('presentation');selected.clear();render()};
const baseAward=window.award,baseDollars=window.giveDollars,basePart=window.participationAward;
function wrap(fn,type,xp,hd){return function(...args){let ids=[...selected],before=JSON.stringify(students);fn(...args);if(JSON.stringify(students)!==before){record(type,ids,typeof xp==='function'?xp(...args):xp,typeof hd==='function'?hd(...args):hd,args[1]||'');selected.clear();render()}}}
window.award=wrap(baseAward,'XP',p=>p,0);window.giveDollars=wrap(baseDollars,'Hero Dollars',0,v=>v);window.participationAward=wrap(basePart,'Participation',2,2);
window.backup=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:11,students,game,extra},null,2)],{type:'application/json'}));a.download='hero-xp-v11-backup.json';a.click()};
window.restore=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result),arr=Array.isArray(d)?d:d.students;if(!Array.isArray(arr)||!arr.every(x=>typeof x.name==='string'&&Number.isFinite(x.xp)))throw Error();if(!confirm('Replace all local data with backup?'))return;students=arr;game=d.game||game;extra=d.extra||extra;save();gameSave();persist();selected.clear();render();toast('Backup restored')}catch{toast('Invalid backup')}};r.readAsText(f)};
const baseUrl=(config.url||'').replace(/\/$/,'');async function api(path,opts={}){let r=await fetch(baseUrl+path,{...opts,headers:{apikey:config.anonKey,Authorization:'Bearer '+cloud.token,'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw Error((await r.text()).slice(0,180));let t=await r.text();return t?JSON.parse(t):null}
window.cloudLogin=async()=>{if(!baseUrl||!config.anonKey)return toast('Configure cloud-config.js first.');try{let r=await fetch(baseUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:el('cloudEmail').value,password:el('cloudPassword').value})});let d=await r.json();if(!r.ok)throw Error(d.error_description||'Sign in failed');cloud={token:d.access_token,user:d.user.id};el('cloudPassword').value='';toast('Signed in — choose Upload or Download.')}catch(e){toast(e.message)}};
window.cloudLogout=()=>{cloud=null;toast('Signed out')};
async function push(silent=false){if(!cloud){if(!silent)toast('Sign in first.');return}if(!silent&&!confirm('Overwrite cloud snapshot with this device data? Back up first.'))return;try{await api('/rest/v1/hero_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:cloud.user,payload:{students,game,extra},updated_at:new Date().toISOString()})});if(!silent)toast('Cloud saved')}catch(e){if(!silent)toast('Cloud error: '+e.message)}}
window.cloudPush=()=>push(false);
window.cloudPull=async()=>{if(!cloud)return toast('Sign in first.');if(!confirm('Replace local data with cloud snapshot? Export backup first.'))return;try{let rows=await api('/rest/v1/hero_state?select=payload&user_id=eq.'+cloud.user),d=rows?.[0]?.payload;if(!d?.students)return toast('No cloud snapshot found.');students=d.students;game=d.game||game;extra=d.extra||extra;save();gameSave();persist();selected.clear();render();toast('Cloud loaded')}catch(e){toast('Cloud error: '+e.message)}};
function queueSync(){clearTimeout(cloudTimer);if(cloud)cloudTimer=setTimeout(()=>push(true),2500)}
const oldSave=window.save,oldGameSave=window.gameSave;window.save=()=>{oldSave();queueSync()};window.gameSave=()=>{oldGameSave();queueSync()};
})();
