(()=>{'use strict';
const b=window.v11bridge, E=id=>document.getElementById(id),safe=window.safe||String;
if(!b){alert('Missing v11.js');return}
const v=()=>{let e=b.get();return e.v12??={archived:[],attendance:{},audit:[]}};
let undoStack=[];
const stamp=()=>new Date().toISOString().slice(0,10);
function snapshot(){undoStack.push(JSON.stringify({students,game,extra:b.get()}));if(undoStack.length>20)undoStack.shift()}
function commit(action,detail=''){v().audit.unshift({date:new Date().toISOString(),action,detail});v().audit=v().audit.slice(0,300);save();gameSave();b.persist();render()}
function show(title,html){E('v11Title').textContent=title;E('v11Body').innerHTML=html;E('v11Panel').classList.add('open')}
const field=(id,label,value='',type='text')=>`<label style="display:block;margin:8px 0">${label}<input id="${id}" type="${type}" value="${safe(value)}"></label>`;
const one=()=>selected.size===1?[...selected][0]:-1;
const num=id=>{let x=Number(E(id).value);return Number.isSafeInteger(x)&&x>=0&&x<=10000000?x:null};
function roster(){show('👥 Student Roster Manager',`<button onclick="v12Add()">Add Student</button> <button onclick="v12Edit()">Edit Selected</button> <button onclick="v12Archive()">Archive Selected</button><h3>Active (${students.length})</h3>${students.map(s=>safe(s.name)).join(' • ')}<h3>Archived</h3>${v().archived.map((s,i)=>`<p>${safe(s.name)} — ${s.xp} XP <button onclick="v12Restore(${i})">Restore</button> <button onclick="v12Delete(${i})">Delete permanently</button></p>`).join('')||'None'}`)}
function form(i){let s=students[i]||{name:'',xp:0,heroDollars:0,camp:'Olympus',heroTitle:'Adventurer'};show(i<0?'Add Student':'Edit Hero Profile',field('vn','Display name',s.name)+field('vx','XP',s.xp,'number')+field('vd','Hero Dollars',s.heroDollars||0,'number')+field('vc','Base Camp',s.camp||'Olympus')+field('vt','Hero title',s.heroTitle||'Adventurer')+`<button onclick="v12Save(${i})">Save Hero</button>`)}
window.v12Add=()=>form(-1);window.v12Edit=()=>{let i=one();i<0?toast('Select one student first.'):form(i)};
window.v12Save=i=>{let name=E('vn').value.trim(),xp=num('vx'),hd=num('vd');if(!name||name.length>70||xp===null||hd===null||students.some((s,j)=>j!==i&&s.name.toLowerCase()===name.toLowerCase()))return toast('Check name and balances.');snapshot();let old=students[i]?.name,s={...(students[i]||{}),name,xp,heroDollars:hd,camp:E('vc').value.trim().slice(0,60),heroTitle:E('vt').value.trim().slice(0,60)};if(i<0)students.push(s);else students[i]=s;let e=b.get();if(old&&old!==name){if(e.trophies?.[old]){e.trophies[name]=e.trophies[old];delete e.trophies[old]}for(let k of Object.keys(e.done||{})){if(k.includes('|'+old+'|')){e.done[k.replace('|'+old+'|','|'+name+'|')]=e.done[k];delete e.done[k]}}}selected.clear();commit(i<0?'Student added':'Profile edited',name);roster()};
window.v12Archive=()=>{let i=one();if(i<0)return toast('Select one student.');if(!confirm('Archive '+students[i].name+'?'))return;snapshot();let s=students.splice(i,1)[0];v().archived.push(s);selected.clear();game.picked=[];commit('Archived',s.name);roster()};
window.v12Restore=i=>{let s=v().archived[i];if(!s)return;if(students.some(x=>x.name===s.name))return toast('Duplicate name.');snapshot();students.push(v().archived.splice(i,1)[0]);commit('Restored',s.name);roster()};
window.v12Delete=i=>{let s=v().archived[i];if(!s||!confirm('Permanently delete '+s.name+'? Keep a backup first.'))return;snapshot();v().archived.splice(i,1);commit('Archived record deleted',s.name);roster()};
function attendance(){let day=stamp(),a=v().attendance[day]||{};show('📋 Attendance & Check-In',`<p>${day} • Classroom tracking only</p><button onclick="v12AllPresent()">All Present</button> <button onclick="v12AttendanceSave()">Save Attendance</button> <button onclick="v12OnTime()">+5 XP to Present</button>${students.map((s,i)=>`<p>${safe(s.name)} <select data-att="${i}"><option value="unmarked">Unmarked</option>${['present','absent','tardy'].map(x=>`<option value="${x}" ${a[i]===x?'selected':''}>${x}</option>`).join('')}</select></p>`).join('')}`)}
window.v12AllPresent=()=>document.querySelectorAll('[data-att]').forEach(x=>x.value='present');
window.v12AttendanceSave=()=>{let a={};document.querySelectorAll('[data-att]').forEach(x=>a[x.dataset.att]=x.value);snapshot();v().attendance[stamp()]=a;commit('Attendance saved',stamp());attendance()};
window.v12OnTime=()=>{let a={};document.querySelectorAll('[data-att]').forEach(x=>a[x.dataset.att]=x.value);let indices=students.map((s,i)=>a[i]==='present'?i:-1).filter(i=>i>=0);if(!indices.length)return toast('Mark students present first.');if(!confirm('Give +5 XP to '+indices.length+' present students?'))return;snapshot();v().attendance[stamp()]=a;indices.forEach(i=>students[i].xp+=5);commit('On-time XP',indices.map(i=>students[i].name).join(', '));attendance()};
function store(){show('🛍 Hero Store Manager',`${game.shop.map((x,i)=>`<p>${safe(x.name)} — $${x.cost} • ${x.stock} in stock <button onclick="v12Item(${i})">Edit</button> <button onclick="v12RemoveItem(${i})">Remove</button></p>`).join('')}<button onclick="v12Item(-1)">Add Item</button> <button onclick="openV10('store')">Purchasing</button>`)}
window.v12Item=i=>{let x=game.shop[i]||{name:'',cost:100,stock:10};show('Store Item',field('in','Item',x.name)+field('ic','Price',x.cost,'number')+field('is','Stock',x.stock,'number')+`<button onclick="v12SaveItem(${i})">Save</button>`)};
window.v12SaveItem=i=>{let name=E('in').value.trim(),cost=num('ic'),stock=num('is');if(!name||cost===null||stock===null)return toast('Check item values.');snapshot();let item={name:name.slice(0,90),cost,stock};if(i<0)game.shop.push(item);else game.shop[i]=item;commit('Store item saved',name);store()};
window.v12RemoveItem=i=>{if(!game.shop[i]||!confirm('Remove this item?'))return;snapshot();let x=game.shop.splice(i,1)[0];commit('Store item removed',x.name);store()};
function history(){show('↶ V12 Activity & Undo',`<button onclick="v12Undo()" ${undoStack.length?'':'disabled'}>Undo last V12 change (${undoStack.length})</button> <button onclick="openV11('history')">V11 Reward History</button>${v().audit.slice(0,75).map(x=>`<p>${safe(x.date)} • ${safe(x.action)} • ${safe(x.detail)}</p>`).join('')||'No V12 actions yet.'}`)}
window.v12Undo=()=>{if(!undoStack.length||!confirm('Undo last V12 change?'))return;let d=JSON.parse(undoStack.pop());students=d.students;game=d.game;let e=b.get();Object.keys(e).forEach(k=>delete e[k]);Object.assign(e,d.extra);save();gameSave();b.persist();selected.clear();render();history()};
function spotlight(){let i=one();if(i<0)return show('🌟 Spotlight','Select exactly one student.');let s=students[i];show('🌟 Student Spotlight',`<div style="padding:22px;text-align:center;border-radius:18px;background:#32214a;color:#fff"><h1>${safe(s.name)}</h1><h2>${safe(s.heroTitle||'Olympian Adventurer')}</h2><h2>Level ${L(s.xp).l}</h2><p>${s.xp.toLocaleString()} XP • 🪙 $${s.heroDollars||0}</p><p>Base Camp: ${safe(s.camp||'Olympus')}</p></div><button onclick="v12Celebrate()">Celebrate!</button>`)}
window.v12Celebrate=()=>{let i=one();if(i>=0)celebrate(students[i].name,'🌟 HERO SPOTLIGHT','Level '+L(students[i].xp).l)};
window.v12=kind=>({roster,attendance,store,history,spotlight}[kind]||roster)();
const oldRender=render;render=function(){oldRender();let q=(E('heroSearch')?.value||'').toLowerCase(),sort=E('heroSort')?.value||'original',cards=[...document.querySelectorAll('#grid .card')];cards.forEach((c,i)=>{c.dataset.idx=i;c.style.display=students[i].name.toLowerCase().includes(q)?'':'none'});if(sort!=='original')cards.sort((a,b)=>{let x=students[+a.dataset.idx],y=students[+b.dataset.idx];return sort==='name'?x.name.localeCompare(y.name):sort==='camp'?(x.camp||'').localeCompare(y.camp||''):sort==='level'?L(y.xp).l-L(x.xp).l:y.xp-x.xp}).forEach(c=>E('grid').appendChild(c))};
E('heroSearch').addEventListener('input',()=>render());E('heroSort').addEventListener('change',()=>render());render();
})();
