(()=>{'use strict';
const bridge=window.v11bridge, el=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!bridge){console.error('V13 needs v11.js');return}
const ex=bridge.get();ex.v13??={heroes:{},observations:[],boss:{name:'Hydra',phase:0,hp:100,max:100,completed:0},pinEnabled:false};const state=()=>ex.v13;
const persist=()=>{bridge.persist();save();};
const selectedOne=()=>selected.size===1?[...selected][0]:-1;
function show(title,content){el('v11Title').textContent=title;el('v11Body').innerHTML=content;el('v11Panel').classList.add('open')}
const datestr=d=>new Date(d).toLocaleDateString();
const level=s=>L(s.xp).l;
const tier=l=>l>=100?'Olympian':l>=75?'Legendary':l>=50?'Mythic':l>=30?'Champion':l>=20?'Silver':l>=10?'Bronze':'Novice';
const heroRecord=name=>state().heroes[name]??={title:'Hero in Training',art:{}};
function heroes(){let i=selectedOne();if(i<0)return show('🦸 Evolving Heroes','Select exactly one student to customize their hero.');let s=students[i],h=heroRecord(s.name),l=level(s),t=tier(l),art=h.art?.[t]||'';show('🦸 Hero Evolution — '+s.name,`<p><b>Level ${l} · ${esc(t)} Tier</b> · ${s.xp} XP</p><div style="text-align:center">${art?`<img src="${esc(art)}" alt="Hero portrait" style="max-width:180px;max-height:200px;object-fit:contain" onerror="this.style.display='none'">`:'🏛️ No portrait uploaded for this tier'}</div><label>Hero title<input id="v13title" value="${esc(h.title)}"></label><p>Assign artwork by evolution tier. Use an image URL hosted on a district-approved site or GitHub repository. Avoid private sharing links.</p><select id="v13tier">${['Novice','Bronze','Silver','Champion','Mythic','Legendary','Olympian'].map(x=>`<option ${x===t?'selected':''}>${x}</option>`).join('')}</select><input id="v13art" placeholder="https://... image URL" value="${esc(art)}"><button onclick="v13SaveHero()">Save Hero Profile</button><p>Tier changes automatically at Levels 10, 20, 30, 50, 75, and 100.</p>`)}
window.v13SaveHero=()=>{let i=selectedOne();if(i<0)return;let name=students[i].name,h=heroRecord(name),url=el('v13art').value.trim(),t=el('v13tier').value;if(url&&!/^https:\/\//i.test(url))return toast('Use an HTTPS image URL.');h.title=el('v13title').value.trim().slice(0,70)||'Hero in Training';h.art??={};h.art[t]=url;state().heroes[name]=h;persist();heroes()};
const stages=[{name:'Hydra',max:100},{name:'Minotaur',max:150},{name:'Medusa',max:200},{name:'Typhon',max:300}];
function boss(){let b=state().boss,phase=stages[b.phase]||stages[0];show('🐍 Multi-Stage Boss Battle',`<h3>${esc(phase.name)} · Stage ${b.phase+1} / ${stages.length}</h3><div style="height:22px;background:#d2c5b4;border-radius:12px;overflow:hidden"><div style="height:100%;background:#7b4264;width:${Math.max(0,b.hp/b.max*100)}%"></div></div><p><b>${b.hp} / ${b.max} HP</b></p><button onclick="v13Damage(5)">⚔️ 5 Damage</button><button onclick="v13Damage(10)">⚔️ 10 Damage</button><button onclick="v13Damage(25)">⚔️ 25 Damage</button><button onclick="v13Damage(50)">⚔️ 50 Damage</button><p>Teacher-confirmed class actions deal damage. No automatic student XP is awarded by boss damage.</p><button onclick="v13BossReset()">Reset Battle (confirmation)</button>`)}
window.v13Damage=n=>{let b=state().boss;b.hp=Math.max(0,b.hp-n);if(b.hp===0){b.completed++;if(b.phase<stages.length-1){b.phase++;b.name=stages[b.phase].name;b.max=stages[b.phase].max;b.hp=b.max;toast('Stage defeated! Next: '+b.name)}else{b.phase=0;b.name=stages[0].name;b.max=100;b.hp=100;toast('Olympus defended! All stages completed.')}}persist();boss()};
window.v13BossReset=()=>{if(!confirm('Reset the boss battle?'))return;state().boss={name:'Hydra',phase:0,hp:100,max:100,completed:0};persist();boss()};
function tracker(){let i=selectedOne();show('📋 Behavior & Work Tracker',`<p>Private teacher observations. Select one student to record an observation. Avoid sensitive descriptions.</p>${i>=0?`<b>${esc(students[i].name)}</b><select id="v13category"><option>Participation</option><option>Work completion</option><option>CHAMPS</option><option>Readiness</option><option>Perseverance</option></select><select id="v13result"><option>Met expectation</option><option>Making progress</option><option>Needs support</option></select><input id="v13note" maxlength="180" placeholder="Optional brief teacher note"><button onclick="v13Record()">Save Observation</button>`:'Select exactly one student.'}<h3>Recent observations</h3>${state().observations.slice(0,35).map(o=>`<p>${esc(datestr(o.date))} · ${esc(o.student)} · ${esc(o.category)} · ${esc(o.result)} ${o.note?'— '+esc(o.note):''}</p>`).join('')||'None yet.'}`)}
window.v13Record=()=>{let i=selectedOne();if(i<0)return;state().observations.unshift({date:new Date().toISOString(),student:students[i].name,category:el('v13category').value,result:el('v13result').value,note:el('v13note').value.trim().slice(0,180)});state().observations=state().observations.slice(0,2000);persist();tracker()};
function weekly(){let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6);return d}
function stats(s){let since=weekly();let h=ex.history||[];let rows=h.filter(x=>new Date(x.date)>=since&&(x.students||[]).includes(s.name));return {events:rows.length,xp:rows.reduce((a,x)=>a+(Number(x.xp)||0),0),hd:rows.reduce((a,x)=>a+(Number(x.hd)||0),0),observations:state().observations.filter(o=>o.student===s.name&&new Date(o.date)>=since).length}}
function analytics(){let rows=students.map(s=>({...stats(s),name:s.name,level:level(s),total:s.xp}));let total=rows.reduce((a,x)=>a+x.xp,0);show('📊 Progress Analytics',`<p>Last 7 calendar days. Historical rewards from before V11 logging are unavailable; XP gains are based on recorded actions, not lifetime differences.</p><p><b>${students.length} active heroes · ${total} recorded weekly XP awards</b></p><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><tr><th>Hero</th><th>Level</th><th>Weekly XP</th><th>Hero $</th><th>Actions</th></tr>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.level}</td><td>${r.xp}</td><td>${r.hd}</td><td>${r.events}</td></tr>`).join('')}</table></div>`)}
function reports(){show('🖨 Weekly Hero Reports',`<p>Choose a student and print a one-page report. This uses available recorded history from the last seven days.</p><select id="v13reportstudent">${students.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('')}</select><button onclick="v13PrintReport()">Print / Save PDF</button>`)}
window.v13PrintReport=()=>{let i=Number(el('v13reportstudent').value),s=students[i];if(!s)return;let r=stats(s),t=ex.trophies?.[s.name]||[];let w=window.open('','_blank');if(!w)return toast('Allow pop-ups to print the report.');w.document.write(`<!doctype html><html><head><title>Hero Report</title><style>body{font-family:Arial;max-width:700px;margin:45px auto;color:#25222b}h1{color:#624580}p{line-height:1.7}</style></head><body><h1>🏛️ Weekly Hero Report</h1><h2>${esc(s.name)}</h2><p>Period: ${esc(datestr(weekly()))} – ${esc(datestr(new Date()))}</p><p><b>Level:</b> ${level(s)} · <b>Lifetime XP:</b> ${s.xp} · <b>Hero Dollars:</b> ${s.heroDollars||0}</p><p><b>Recorded weekly XP awards:</b> ${r.xp} · <b>Hero Dollars earned (logged):</b> ${r.hd}</p><p><b>Recorded reward actions:</b> ${r.events} · <b>Teacher observations:</b> ${r.observations}</p><p><b>Achievements:</b> ${t.map(esc).join(', ')||'Keep growing!'}</p><hr><p>Purpose • Adventure • Defying Gravity • Go the Distance</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
function security(){show('🔐 Teacher Access & Privacy',`<p><b>Important:</b> This GitHub Pages site is static and publicly readable. A PIN inside JavaScript cannot securely protect teacher controls or student information.</p><p>For genuine teacher-only access, use authenticated hosting with server-side authorization and private student records. The existing Supabase sign-in protects cloud API data when Row Level Security is configured, but does not protect public website code or browser-local records.</p><p>Until that is deployed, use Presentation Mode for projection and do not enter sensitive behavior notes into a publicly accessible or shared-browser installation.</p><button onclick="togglePresentation();document.getElementById('v11Panel').classList.remove('open')">Enter Presentation Mode</button>`)}
window.v13Open=k=>({heroes,boss,tracker,analytics,reports,security}[k]||security)();
// Preserve the V11 backup structure; V13 lives inside extra and is included automatically.
})();