(()=>{'use strict';
const bridge=window.v11bridge;if(!bridge){console.error('V14 requires v11.js');return;}
const extra=bridge.get();extra.v14??={presets:[{id:'scholar',name:'Outstanding Scholar',xp:5,hd:10},{id:'champ',name:'CHAMPS Champion',xp:3,hd:2},{id:'beyond',name:'Above & Beyond',xp:10,hd:5}],teams:{},participation:{},attendanceAwards:{},lastBackup:''};
const state=()=>extra.v14, el=id=>document.getElementById(id), esc=window.safe||((s)=>String(s));
function persist(){bridge.persist();}
function show(title,body){el('v11Title').textContent=title;el('v11Body').innerHTML=body;el('v11Panel').classList.add('open');}
function dateKey(){return new Date().toLocaleDateString('en-CA');}
function weekKey(){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(d.getDay()+6)%7);return d.toLocaleDateString('en-CA');}
function syncCount(){let n=selected.size;let e=el('v14count');if(e)e.textContent=n+' selected';}
new MutationObserver(syncCount).observe(el('grid'),{childList:true});syncCount();
function home(){let today=dateKey(),a=extra.v12?.attendance?.[today]||{},present=Object.values(a).filter(x=>x==='present').length;let completed=Object.keys(extra.done||{}).filter(k=>k.includes(today)).length;show('🏠 Daily Classroom Dashboard',`<div class="mission"><h3>${today}</h3><p>Heroes: <b>${students.length}</b> · Marked present: <b>${present}</b> · Daily mission records: <b>${completed}</b></p><p>CHAMPS Voice Level: <b>${game.voice}</b> · Class Quest: <b>${game.quest.progress}/${game.quest.goal}</b></p><p>Boss: <b>${esc(game.boss.name)}</b> · ${game.boss.hp}/${game.boss.max} HP</p></div><button onclick="v12('attendance')">Attendance</button><button onclick="openV11('missions')">Missions</button><button onclick="openV10('champs')">CHAMPS</button><button onclick="openTimer()">Timer</button>`);}
function presets(){show('✨ Smart Reward Presets',`<p>Select students, then award a preset. Every award requires confirmation.</p>${state().presets.map(p=>`<div class="mission"><b>${esc(p.name)}</b> · +${p.xp} XP / +$${p.hd}<p><button onclick="v14AwardPreset('${p.id}')">Award</button><button onclick="v14EditPreset('${p.id}')">Edit</button><button onclick="v14DeletePreset('${p.id}')">Delete</button></p></div>`).join('')}<button onclick="v14EditPreset('')">Add Preset</button>`);}
window.v14EditPreset=id=>{let p=state().presets.find(x=>x.id===id)||{id:'',name:'',xp:0,hd:0};show('Reward Preset',`<label>Name<input id="v14pn" value="${esc(p.name)}"></label><label>XP<input type="number" id="v14px" min="0" max="10000" value="${p.xp}"></label><label>Hero Dollars<input type="number" id="v14ph" min="0" max="10000" value="${p.hd}"></label><button onclick="v14SavePreset('${id}')">Save</button>`);};
window.v14SavePreset=id=>{let name=el('v14pn').value.trim(),xp=Number(el('v14px').value),hd=Number(el('v14ph').value);if(!name||name.length>65||![xp,hd].every(x=>Number.isSafeInteger(x)&&x>=0&&x<=10000)||xp+hd===0)return toast('Enter a valid name and reward.');let p=state().presets.find(x=>x.id===id);if(p)Object.assign(p,{name,xp,hd});else state().presets.push({id:'p'+Date.now(),name,xp,hd});persist();presets();};
window.v14DeletePreset=id=>{if(!confirm('Delete this preset?'))return;state().presets=state().presets.filter(x=>x.id!==id);persist();presets();};
window.v14AwardPreset=id=>{let p=state().presets.find(x=>x.id===id);if(!p||!selected.size)return toast('Select heroes first.');let ids=[...selected],names=ids.map(i=>students[i]?.name).filter(Boolean);if(!confirm(`Award ${p.name} (+${p.xp} XP and +$${p.hd}) to ${names.length} heroes?\n${names.join(', ')}`))return;history.push(JSON.stringify(students));let leveled=[];ids.forEach(i=>{let s=students[i],before=L(s.xp).l;s.xp+=p.xp;s.heroDollars=(s.heroDollars||0)+p.hd;if(L(s.xp).l>before)leveled.push(s.name);});save();if(p.xp)playXPSound();if(p.hd)playCoinSound();if(leveled.length)playLevelSound();extra.history??=[];extra.history.unshift({date:new Date().toISOString(),type:'V14 Preset',students:names,xp:p.xp,hd:p.hd,note:p.name});persist();selected.clear();render();presets();toast('Preset awarded to '+names.length+' heroes.');};
function teams(){let camps=[...new Set(students.map(s=>s.camp||'Olympus'))].sort();show('🏕 Base Camp Challenges',`<p>Team points are separate from personal XP and Hero Dollars.</p><label>Challenge name<input id="v14challenge" placeholder="e.g. Temple of Teamwork" value="${esc(state().challenge||'Temple of Teamwork')}"></label>${camps.map(c=>`<div class="mission"><b>${esc(c)}</b> — ${state().teams[c]||0} team points <button onclick="v14Team('${encodeURIComponent(c)}',5)">+5</button><button onclick="v14Team('${encodeURIComponent(c)}',10)">+10</button></div>`).join('')}<button onclick="v14ResetTeams()">Reset Team Challenge</button>`);}
window.v14Team=(encoded,n)=>{let c=decodeURIComponent(encoded);state().challenge=el('v14challenge').value.slice(0,70);state().teams[c]=(state().teams[c]||0)+n;persist();teams();};
window.v14ResetTeams=()=>{if(!confirm('Reset team points? Student XP will not change.'))return;state().teams={};persist();teams();};
function attendance(){let a=extra.v12?.attendance?.[dateKey()]||{},eligible=students.map((s,i)=>a[i]==='present'?i:-1).filter(i=>i>=0),paid=state().attendanceAwards[dateKey()]||[];show('✓ One-Click Attendance Rewards',`<p>Present: ${eligible.length} · Already rewarded: ${paid.length}. Only students marked present and not yet rewarded today are eligible.</p><p><b>${eligible.filter(i=>!paid.includes(students[i].name)).map(i=>esc(students[i].name)).join(', ')||'No eligible students'}</b></p><button onclick="v12('attendance')">Mark Attendance</button><button onclick="v14AttendanceAward()">Award +5 XP to Eligible</button>`);}
window.v14AttendanceAward=()=>{let day=dateKey(),a=extra.v12?.attendance?.[day]||{},paid=state().attendanceAwards[day]||[],ids=students.map((s,i)=>a[i]==='present'&&!paid.includes(s.name)?i:-1).filter(i=>i>=0);if(!ids.length)return toast('No unawarded present heroes.');if(!confirm('Award +5 XP to '+ids.length+' present heroes?'))return;history.push(JSON.stringify(students));ids.forEach(i=>students[i].xp+=5);state().attendanceAwards[day]=paid.concat(ids.map(i=>students[i].name));extra.history??=[];extra.history.unshift({date:new Date().toISOString(),type:'V14 On Time',students:ids.map(i=>students[i].name),xp:5,hd:0,note:'Attendance reward'});save();persist();render();playXPSound();attendance();};
function participation(){let week=weekKey(),counts=state().participation[week]||{};show('🙋 Fair Participation Tracker',`<p>Weekly participation opportunities (not automatic XP awards). Choose a student or pick someone with the fewest turns.</p><button onclick="v14FairPick()">🎲 Fair Pick</button><button onclick="v14ResetParticipation()">Reset Week</button>${students.map(s=>`<div class="historyline">${esc(s.name)} — <b>${counts[s.name]||0}</b> turns <button onclick="v14MarkParticipation('${encodeURIComponent(s.name)}')">+1 Turn</button></div>`).join('')}`);}
window.v14MarkParticipation=encoded=>{let name=decodeURIComponent(encoded),week=weekKey();state().participation[week]??={};state().participation[week][name]=(state().participation[week][name]||0)+1;persist();participation();};
window.v14FairPick=()=>{let week=weekKey(),counts=state().participation[week]||{},min=Math.min(...students.map(s=>counts[s.name]||0)),pool=students.filter(s=>(counts[s.name]||0)===min),s=pool[Math.floor(Math.random()*pool.length)];if(!s)return;state().participation[week]??={};state().participation[week][s.name]=(state().participation[week][s.name]||0)+1;persist();participation();toast('🎲 '+s.name+' selected!');};
window.v14ResetParticipation=()=>{if(!confirm('Reset this week’s turn counts?'))return;state().participation[weekKey()]={};persist();participation();};
function backups(){let last=state().lastBackup||'No backup recorded',days=state().lastBackup?Math.floor((Date.now()-Date.parse(state().lastBackup))/86400000):null;show('💾 Backup Reminders',`<p>Last recorded backup: <b>${esc(last)}</b></p><p>${days===null?'Please create a backup.':days>=7?'Your last recorded backup is at least 7 days old.':'Backup reminder is up to date.'}</p><button onclick="v14Backup()">Download Full Backup</button><p>Backups contain student information. Keep them in district-approved secure storage.</p>`);}
window.v14Backup=()=>{state().lastBackup=new Date().toISOString();persist();backup();backups();};
window.v14Open=type=>({home,presets,teams,attendance,participation,backups}[type]||home)();
// Wrap backups without altering V11's existing student/game/extras backup format.
let reminder=document.createElement('div');reminder.id='v14home';reminder.innerHTML='<div class="stats"><span>🏛️ <b>Olympus Academy</b></span><span id="v14summary"></span><button type="button" onclick="v14Open(\'home\')">Daily Overview</button></div>';let main=document.querySelector('main');if(main)main.insertBefore(reminder,main.firstChild);
function summary(){let a=extra.v12?.attendance?.[dateKey()]||{},present=Object.values(a).filter(x=>x==='present').length;el('v14summary').textContent=`${students.length} heroes · ${present} present · Voice ${game.voice} · Quest ${game.quest.progress}/${game.quest.goal}`;}
summary();new MutationObserver(summary).observe(el('grid'),{childList:true});
if(!state().lastBackup||Date.now()-Date.parse(state().lastBackup)>7*86400000){setTimeout(()=>toast('💾 Reminder: back up your Hero Academy data.'),1600);}
})();
